### ISSUE TITLE
Found some bugs with prev and next

### ISSUE THREAD

**Issue by SimeonC** [brunobertolini/pagix#13]
The following 2 scenarios returned false when they should have returned a page value.

```js
pagix({ records: 9, limit: 1, current: 7 });
// outputs
{
  current: 7,
  end: [9],
  from: 7,
  middle: [5, 6, 7, 8],
  next: false,
  prev: 4,
  start: [1],
  to: 7,
  total: 9
}
```

```js
pagix({records: 9, limit: 3, current: 1});
// outputs
{
  current: 1,
  end: [3],
  from: 1,
  middle: [2],
  next: false, // should be 2
  prev: false,
  start: [1],
  to: 3,
  total: 3
}
```

**Comment by brunobertolini** [comment]
Hi @SimeonC , thanks a lot for your contribution!

I was analizing this cases [codesandbox example](https://codesandbox.io/s/loving-mclaren-4265rwmzlx) to understand, and they are correctly. The expected behaviour is `false` in both, because `prev` and `next` refer to dots button on example, and return false when not have the button.

Maybe we can change names to avoid confusion, have you a suggestion?

If you can create a new PR with only TS types, I can merge soon!

**Comment by SimeonC** [comment]
Ahhh, I see. I think that's a bit misleading naming as usually next is current+1, prev is current-1. Maybe `skipNext` or `truncateNext` might be clearer? Now that I reread the docs it's clearer to me what it means but it's a bit easy to miss what "next" is being used as in pagix.

I'll create a new PR on Monday with just the types.

**Comment by SimeonC** [comment]
If your OK with it I can try make the Readme a bit clearer?

**Comment by brunobertolini** [comment]
> If your OK with it I can try make the Readme a bit clearer?

go ahead! 😃
